[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ChromeDevToolsLite = "fd981815-49ad-43be-956f-1ba144983534"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
